// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByU-vR58me1cUtGKicXSMdQ-nFx3stkug',
    appId: '1:367700613467:web:72c3d7ff1f1094b352627e',
    messagingSenderId: '367700613467',
    projectId: 'thunder-test-project',
    authDomain: 'thunder-test-project.firebaseapp.com',
    storageBucket: 'thunder-test-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdg_q_YyZjzEnpKFoqNEyhC7alce3ZWeU',
    appId: '1:367700613467:android:ff5a6046a422ddd652627e',
    messagingSenderId: '367700613467',
    projectId: 'thunder-test-project',
    storageBucket: 'thunder-test-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOOpInqhQB1LSkr6PbZtLt0smsUgmXTV0',
    appId: '1:367700613467:ios:6761a2caead37e7e52627e',
    messagingSenderId: '367700613467',
    projectId: 'thunder-test-project',
    storageBucket: 'thunder-test-project.appspot.com',
    iosBundleId: 'com.example.indiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOOpInqhQB1LSkr6PbZtLt0smsUgmXTV0',
    appId: '1:367700613467:ios:6761a2caead37e7e52627e',
    messagingSenderId: '367700613467',
    projectId: 'thunder-test-project',
    storageBucket: 'thunder-test-project.appspot.com',
    iosBundleId: 'com.example.indiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByU-vR58me1cUtGKicXSMdQ-nFx3stkug',
    appId: '1:367700613467:web:3ef05de3f98d8d7352627e',
    messagingSenderId: '367700613467',
    projectId: 'thunder-test-project',
    authDomain: 'thunder-test-project.firebaseapp.com',
    storageBucket: 'thunder-test-project.appspot.com',
  );
}
